import type { NextPage } from 'next'
import Head from 'next/head'
import MainLayout from '../components/layouts/MainLayout'

const Home: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="">Test ts next prj</h1>
      <MainLayout />
    </div>
  )
}

export default Home
